export const GOOGLE_FORM_URL = "https://forms.gle/tcbhHKgMNcecePzC6";

export const siteConfig = {
  name: "VAIORA’26",
  title: "VAIORA’26 | Vaigai College of Engineering",
  description:
    "VAIORA’26 – An Inter Collegiate Symposium organized by the Department of Computer Science and Engineering, Vaigai College of Engineering, Madurai.",
  college: {
    name: "VAIGAI COLLEGE OF ENGINEERING",
    accreditation: "Approved by AICTE, Affiliated to Anna University",
    department: "DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING",
    address: "Therkkutheru, Vinayagapuram, Melur, Madurai - 625 122",
  },
  event: {
    name: "VAIORA’26",
    edition: "2026",
    type: "AN INTER COLLEGIATE SYMPOSIUM",
    tagline: "LET IDEAS TAKE FLIGHT",
    venue: "KALAM AUDITORIUM",
    date: "8th OCTOBER, 2026",
    time: "9:00 AM",
    googleFormUrl: GOOGLE_FORM_URL,
  },
  scheduleSlots: [
    {
      slot: "SLOT 1",
      timing: "10:00 AM - 11:00 AM",
      type: "session",
      technical: ["Paper Presentation", "Code Clash"],
      nonTechnical: ["Connection", "Missing Word"],
    },
    {
      slot: "BREAK",
      timing: "11:00 AM - 11:30 AM",
      type: "break",
      title: "Break (Refreshment)",
      detail: "Refreshments & Campus Networking at Cafeteria",
    },
    {
      slot: "SLOT 2",
      timing: "11:30 AM - 1:00 PM",
      type: "session",
      technical: ["Project Expo", "UI / UX Design"],
      nonTechnical: ["IPL Auction", "Video Editing"],
    },
  ],
  technicalEvents: [
    {
      id: "paper-presentation",
      name: "PAPER PRESENTATION",
      badge: "TECH 01",
      slot: "SLOT 1",
      timing: "10:00 AM - 11:00 AM",
      description: "Event details will be announced soon.",
      icon: "FileText",
    },
    {
      id: "code-clash",
      name: "CODE CLASH",
      badge: "TECH 02",
      slot: "SLOT 1",
      timing: "10:00 AM - 11:00 AM",
      description: "Event details will be announced soon.",
      icon: "Terminal",
    },
    {
      id: "project-expo",
      name: "PROJECT EXPO",
      badge: "TECH 03",
      slot: "SLOT 2",
      timing: "11:30 AM - 1:00 PM",
      description: "Event details will be announced soon.",
      icon: "Cpu",
    },
    {
      id: "ui-ux-design",
      name: "UI / UX DESIGN",
      badge: "TECH 04",
      slot: "SLOT 2",
      timing: "11:30 AM - 1:00 PM",
      description: "Event details will be announced soon.",
      icon: "Palette",
    },
  ],
  nonTechnicalEvents: [
    {
      id: "connection",
      name: "CONNECTION",
      badge: "NON-TECH 01",
      slot: "SLOT 1",
      timing: "10:00 AM - 11:00 AM",
      description: "Event details will be announced soon.",
      icon: "Sparkles",
    },
    {
      id: "missing-word",
      name: "MISSING WORD",
      badge: "NON-TECH 02",
      slot: "SLOT 1",
      timing: "10:00 AM - 11:00 AM",
      description: "Event details will be announced soon.",
      icon: "HelpCircle",
    },
    {
      id: "ipl-auction",
      name: "IPL AUCTION",
      badge: "NON-TECH 03",
      slot: "SLOT 2",
      timing: "11:30 AM - 1:00 PM",
      description: "Event details will be announced soon.",
      icon: "Trophy",
    },
    {
      id: "video-editing",
      name: "VIDEO EDITING",
      badge: "NON-TECH 04",
      slot: "SLOT 2",
      timing: "11:30 AM - 1:00 PM",
      description: "Event details will be announced soon.",
      icon: "Film",
    },
  ],
  pillars: [
    {
      title: "INNOVATE",
      description: "Explore ideas and emerging technology.",
      badge: "01",
    },
    {
      title: "COMPETE",
      description: "Challenge yourself through engaging events.",
      badge: "02",
    },
    {
      title: "CONNECT",
      description: "Meet students and innovators from different colleges.",
      badge: "03",
    },
    {
      title: "CREATE",
      description: "Turn creativity into meaningful solutions.",
      badge: "04",
    },
  ],
  journey: [
    { step: "01", title: "REGISTER", detail: "Secure your entry pass online" },
    { step: "02", title: "EXPLORE", detail: "Experience technical realms" },
    { step: "03", title: "COMPETE", detail: "Put skills to the ultimate test" },
    { step: "04", title: "CONNECT", detail: "Build lifelong network" },
    { step: "05", title: "CREATE", detail: "Shape future breakthroughs" },
  ],
  coordinators: {
    chief: {
      name: "Dr. Sivaranjani Rajamanickam",
      role: "Chief Coordinator",
      designation: "Principal",
      institution: "Vaigai College of Engineering, Madurai",
    },
    faculty: [
      {
        name: "N. Roobika",
        role: "Faculty Coordinator",
        designation: "AP / CSE",
      },
      {
        name: "S. Shamli",
        role: "Faculty Coordinator",
        designation: "AP / CSE",
      },
    ],
    students: [
      {
        name: "Hari Vignesh",
        role: "Student Coordinator",
        phone: "8110885955",
        displayPhone: "+91 81108 85955",
      },
      {
        name: "Afrin Sahana",
        role: "Student Coordinator",
        phone: "7094181668",
        displayPhone: "+91 70941 81668",
      },
    ],
  },
};
